const tg=window.Telegram.WebApp;tg.ready();tg.expand();
const auth=tg.initData;
const headers=()=>({"Content-Type":"application/json","Authorization":"tma "+auth});
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d}
function setPage(page){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));const el=document.getElementById(page);if(el)el.classList.remove("hidden");document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));if(page==="referrals")loadReferrals();if(page==="admin")loadAdminChannels()}
async function loadMe(){if(!auth){alert("Open this Mini App from Telegram.");return null}const d=await api("/api/me");document.getElementById("balance").textContent=Number(d.balance).toLocaleString()+" ZIBSOL";document.getElementById("gram").textContent=d.gram+" GRAM";document.getElementById("avatar").textContent=(d.user.first_name||"Z")[0].toUpperCase();if(d.is_admin){document.getElementById("adminTab").classList.remove("hidden");}else{document.getElementById("navAdmin").classList.add("hidden")}return d}
async function loadChannels(){const el=document.getElementById("channels");try{const rows=await api("/api/channels");if(!rows.length){el.innerHTML='<div class="info-card"><b>No channels configured yet.</b><span>Come back later for new earning tasks.</span></div>';return}el.innerHTML=rows.map(c=>`<div class="channel"><div class="row"><strong>${esc(c.title)}</strong><strong style="color:#16e6a4">+${Number(c.reward).toLocaleString()}</strong></div><div class="row"><a href="${esc(c.join_link)}" target="_blank">Join channel →</a><button onclick="claim(${c.id})">Verify membership</button></div></div>`).join("")}catch(e){el.textContent=e.message}}
async function claim(id){try{const d=await api("/api/channels/claim",{method:"POST",body:JSON.stringify({channel_id:id})});alert("+"+Number(d.reward).toLocaleString()+" ZIBSOL");await loadMe()}catch(e){alert(e.message)}}
async function loadReferrals(){try{const d=await api("/api/referral");document.getElementById("refCount").textContent=d.count;document.getElementById("refReward").textContent=Number(d.reward_per_ref).toLocaleString()+" ZIBSOL";document.getElementById("refTotal").textContent=Number(d.total_earned).toLocaleString();document.getElementById("refLink").value=d.link;window.referralLink=d.link}catch(e){document.getElementById("refMsg").textContent=e.message}}
async function copyReferral(){try{await navigator.clipboard.writeText(window.referralLink);document.getElementById("refMsg").textContent="Referral link copied."}catch(e){document.getElementById("refMsg").textContent="Copy failed. Long-press the link and copy it."}}
function shareReferral(){const link=window.referralLink;const url="https://t.me/share/url?url="+encodeURIComponent(link)+"&text="+encodeURIComponent("Join ZIBSOL and earn ZIBSOL rewards!");if(tg.openTelegramLink)tg.openTelegramLink(url);else window.open(url,"_blank")}
async function loadAdminChannels(){try{const rows=await api("/api/admin/channels");document.getElementById("adminChannels").innerHTML=rows.map(c=>`<div class="channel"><div class="row"><strong>${esc(c.title)}</strong><span style="color:#16e6a4">${c.active?"ACTIVE":"OFF"}</span></div><div class="row"><span>${esc(c.chat_id)} · +${Number(c.reward).toLocaleString()}</span>${c.active?`<button onclick="disableChannel(${c.id})">Disable</button>`:""}</div></div>`).join("")||'<p class="muted">No channels.</p>'}catch(e){document.getElementById("adminChannels").textContent=e.message}}
async function disableChannel(id){try{await api("/api/admin/channels/disable",{method:"POST",body:JSON.stringify({channel_id:id})});await loadAdminChannels();await loadChannels()}catch(e){alert(e.message)}}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>setPage(b.dataset.page));
document.getElementById("target").oninput=()=>document.getElementById("price").textContent=(Number(document.getElementById("target").value||0)*10).toLocaleString()+" ZIBSOL";
document.getElementById("createCampaign").onclick=async()=>{try{const d=await api("/api/campaigns",{method:"POST",body:JSON.stringify({target_members:Number(document.getElementById("target").value),link:document.getElementById("promoLink").value.trim(),chat_id:document.getElementById("promoChat").value.trim()})});document.getElementById("promoMsg").textContent="Campaign #"+d.campaign_id+" created.";await loadMe()}catch(e){document.getElementById("promoMsg").textContent=e.message}};
document.getElementById("withdrawBtn").onclick=async()=>{try{const d=await api("/api/withdraw",{method:"POST",body:JSON.stringify({wallet:document.getElementById("wallet").value.trim()})});document.getElementById("withdrawMsg").textContent="Withdrawal #"+d.withdrawal_id+" submitted for processing.";await loadMe()}catch(e){document.getElementById("withdrawMsg").textContent=e.message}};
document.getElementById("addChannel").onclick=async()=>{const msg=document.getElementById("adminMsg");msg.textContent="Checking Telegram…";try{const d=await api("/api/admin/channels",{method:"POST",body:JSON.stringify({chat_id:document.getElementById("adminChatId").value.trim(),join_link:document.getElementById("adminJoinLink").value.trim(),reward:Number(document.getElementById("adminReward").value),title:document.getElementById("adminTitle").value.trim()||null})});msg.textContent=`Added ${d.title} — +${Number(d.reward).toLocaleString()} ZIBSOL`;await loadAdminChannels();await loadChannels()}catch(e){msg.textContent=e.message}};
document.getElementById("copyRef").onclick=copyReferral;document.getElementById("shareRef").onclick=shareReferral;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
loadMe().then(()=>Promise.all([loadChannels(),loadReferrals()]));
