(function(){
  const tg=window.Telegram&&window.Telegram.WebApp;
  const auth=()=>tg?tg.initData:"";
  const hdr=()=>({"Content-Type":"application/json","Authorization":"tma "+auth()});
  async function req(path,options={}){const r=await fetch(path,{...options,headers:{...hdr(),...(options.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||("HTTP "+r.status));return d;}
  function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  window.loadChannels=async function(){const el=document.getElementById("channels");if(!el)return;el.innerHTML='<div class="info-card"><b>Loading earning tasks…</b><span>Checking channels and paid promotions.</span></div>';const results=await Promise.allSettled([req("/api/channels"),req("/api/campaigns")]);const channels=results[0].status==='fulfilled'?results[0].value:[];const campaigns=results[1].status==='fulfilled'?results[1].value:[];const errors=results.filter(x=>x.status==='rejected').map(x=>x.reason.message);const items=[];channels.forEach(c=>items.push(`<div class="channel"><div class="row"><strong>📢 ${esc(c.title)}</strong><strong style="color:#16e6a4">+${Number(c.reward).toLocaleString()} ZIBSOL</strong></div><div class="row"><span>Join & verify membership</span><button type="button" onclick="window.__zibsolClaim(${c.id})">Verify membership</button></div><div class="row"><a href="${esc(c.join_link)}" target="_blank">Join channel →</a></div></div>`));campaigns.forEach(c=>{const target=Number(c.target_members||0),joined=Number(c.completed_members||0),pct=target?Math.min(100,Math.round(joined/target*100)):0;items.push(`<div class="channel campaign-card"><div class="row"><strong>📣 ${esc(c.link)}</strong><strong style="color:#16e6a4">+${Number(c.reward_per_member||100).toLocaleString()} ZIBSOL</strong></div><div class="row"><span>${joined} / ${target} verified</span><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="row"><span>Paid promotion</span><button type="button" onclick="window.__zibsolCampaign(${c.id})">Verify & earn</button></div><div class="row"><a href="${esc(c.link)}" target="_blank">Join channel →</a></div></div>`)});let html=items.length?items.join(""):'<div class="info-card"><b>No earning tasks available.</b><span>Come back later for new channels and paid promotions.</span></div>';if(errors.length)html+=`<div class="info-card"><b>Some tasks could not be loaded</b><span>${esc(errors.join(" · "))}</span><button type="button" class="gradient-btn" onclick="window.loadChannels()">↻ Try again</button></div>`;el.innerHTML=html;};
  window.__zibsolClaim=async function(id){try{const d=await req("/api/channels/claim",{method:"POST",body:JSON.stringify({channel_id:id})});alert("+"+Number(d.reward).toLocaleString()+" ZIBSOL");if(window.loadMe)await window.loadMe();await window.loadChannels();}catch(e){alert(e.message)}};
  window.__zibsolCampaign=async function(id){try{const d=await req("/api/campaigns/claim",{method:"POST",body:JSON.stringify({campaign_id:id})});alert("+"+Number(d.reward).toLocaleString()+" ZIBSOL");if(window.loadMe)await window.loadMe();await window.loadChannels();}catch(e){alert(e.message)}};
  window.loadDeveloper=async function(){const stats=document.getElementById("devStats"),users=document.getElementById("devUsers"),wd=document.getElementById("devWithdrawals");if(stats)stats.innerHTML='<div class="info-card"><span>Loading developer statistics…</span></div>';if(users)users.innerHTML='<div class="info-card"><span>Loading members…</span></div>';if(wd)wd.innerHTML='<div class="info-card"><span>Loading withdrawal requests…</span></div>';const [s,u,w]=await Promise.allSettled([req("/api/developer/stats"),req("/api/developer/users"),req("/api/developer/withdrawals")]);if(stats){if(s.status==='fulfilled'){const x=s.value;stats.innerHTML=`<div class="dev-stat"><small>MEMBERS</small><strong>${Number(x.users).toLocaleString()}</strong></div><div class="dev-stat"><small>CIRCULATING</small><strong>${Number(x.circulating).toLocaleString()}</strong><span>ZIBSOL</span></div><div class="dev-stat"><small>PENDING WITHDRAWALS</small><strong>${Number(x.pending_withdrawals).toLocaleString()}</strong></div><div class="dev-stat"><small>ACTIVE CAMPAIGNS</small><strong>${Number(x.active_campaigns).toLocaleString()}</strong></div>`}else stats.innerHTML=`<div class="info-card"><b>Developer statistics unavailable</b><span>${esc(s.reason?.message||"Unknown error")}</span></div>`}if(wd){if(w.status==='fulfilled'){const rows=w.value;wd.innerHTML=rows.length?rows.map(x=>`<div class="wd-row"><div class="row"><strong>#${x.id} · ${esc(x.username?"@"+x.username:(x.first_name||"User"))}</strong><span class="${x.status==='pending'?"warning":x.status==='approved'?"success":"danger"}">${esc(x.status)}</span></div><div class="row"><span>${Number(x.amount).toLocaleString()} ZIBSOL → ${x.gram} GRAM</span></div><div class="tiny">Wallet: ${esc(x.wallet)}</div>${x.status==='pending'?`<div class="dev-actions"><button type="button" onclick="window.__approveWithdrawal(${x.id})">✅ Approve</button><button type="button" onclick="window.__rejectWithdrawal(${x.id})">↩ Reject & refund</button></div>`:""}</div>`).join(""):'<div class="info-card"><span>No withdrawal requests.</span></div>'}else wd.innerHTML=`<div class="info-card"><b>Withdrawal data unavailable</b><span>${esc(w.reason?.message||"Unknown error")}</span></div>`}if(users){if(u.status==='fulfilled'){const rows=u.value;users.innerHTML=rows.length?rows.map(x=>`<div class="user-row"><div class="row"><strong>${esc(x.username?"@"+x.username:(x.first_name||"User"))}</strong><strong>${Number(x.balance).toLocaleString()} ZIBSOL</strong></div><div class="tiny">ID: ${x.id} · Referrals: ${x.referrals} · Wallet: ${esc(x.wallet||"not connected")}</div></div>`).join(""):'<div class="info-card"><span>No members yet.</span></div>'}else users.innerHTML=`<div class="info-card"><b>Member data unavailable</b><span>${esc(u.reason?.message||"Unknown error")}</span></div>`}};
  window.__approveWithdrawal=async function(id){if(!confirm("Approve this withdrawal for manual GRAM payout?"))return;try{await req("/api/developer/withdrawals/approve",{method:"POST",body:JSON.stringify({withdrawal_id:id})});await window.loadDeveloper()}catch(e){alert(e.message)}};
  window.__rejectWithdrawal=async function(id){if(!confirm("Reject and refund this withdrawal?"))return;try{await req("/api/developer/withdrawals/reject",{method:"POST",body:JSON.stringify({withdrawal_id:id})});await window.loadDeveloper();if(window.loadMe)await window.loadMe()}catch(e){alert(e.message)}};
})();
